language: node_js
stages:
- test
- name: deploy
  if: branch IN (master)
jobs:
  include:
  - stage: test
    install: true
    script:
    - echo "tests here"
  - stage: deploy
    services: docker
    install: true
    script:
    - docker run -it -e JENKINS_AUTH_TOKEN=$JENKINS_AUTH_TOKEN -e JENKINS_BUILD_TOKEN=$JENKINS_BUILD_TOKEN
      -e JENKINS_BUILD_PROJECT=$TRAVIS_REPO_SLUG -e JENKINS_BUILD_BRANCH=$TRAVIS_BRANCH
      p1hub/p1jenkinstrigger
notifications:
  slack:
    secure: W49+rluCQgNYGjxCliB9pBsknGeQ7FSGnm3yDy/jdqcuktOOeaXkMUScYKYeGMvnTEzpX5n2o/nREL+o5ZXzUr6sz/6aOeOzz0/RuQh4+7L7ZZ9ENfs/brQD/D3AobiQRip5iV2Rbl1NURhjRXTV9nIZ+jSY2XpO0AwPFV64CGtzOpbuWmZCmcJfKFy9Pe4+8ARO60fpuCqEKKBVY6SWn1qCrZ+w2UbFTS5byXP1sZsPyXIeT7vIG3Dr35ngThwpBWKw8N3tBUIrpKrQr5pcIJsvtuFHa7f2NZTV57hpxE730J5TA5PFvLjXFF1cPHzpu5DYcHoYhik/LdPQcfZw1xOa++znDLPYAvjsRJ3yT3gJuouGWBAcK5WT7411yQSqGEVkp3eX8jQIsClRUjhaNE1ooZIAgz0K4Wlj9WmhyzyRcwAYbR4l0OjnffNai+KhrV34kzGEhxg/xN1bLmBBZMM0hVDKSJfeu9+f6dTSyvjQpzQlGSH5ewwA+85W+ItfnEEvSU4Vj5NuW3YEywEeexDaclI8wNEoBrbZ5K5dSRj73y1Q6xA1w8yc9lLT1cTIaV+qCnxhjigTE8r/HR6Gm/dNIcnw/c6JMOgNL/q2hOmYdTzwTFy5i3qWL1jm8r6I/TLsCtOlqeaIAS3mZjGdRXO3B31Gjpp6QUC8Ohs0KKY=
